version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "socket-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-888888"
s3_prefix = "socket-demo-s3"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = 'TableName="connections"  '